combine_threshold: 50
config_file: config.yaml
debug: false
dilate: true
input_dir: input
kernel_size: 5
max_workers: 8
output_dir: output
output_format: null
pad_height: 0
pad_width: 8
phrases:
- "Playtest Card \u2014 Not for sale"
- WillieTanner Proxy e NOT FOR SALE
- Proxy e NOT FOR SALE
- "\xAB Not for Sale \xA2 TTP Proxy \xA2"
- "Not for Sale \xA2 TTP Proxy \xA2"
- "Custom Proxy \xAB NOT FOR SALE"
- Custom Proxy e NOT FOR SALE
- Playtest Card - Not for sale
- mpcautofill.com
- not for sanctioned play
- proxy by deelight
- Not for sale!
- Not for sale
- Playtest Card-
- Playtest Card -
- Playtest Card
- Custom Proxy
- TTP Proxy
- WillieTanner Proxy Not for sale
- WillieTanner Proxy
- PsilosX Proxy
- Custom Proxy
- Proxy
tesseract_cmd: tesseract
